### ISSUE TITLE
Authentification only works for one site

### ISSUE THREAD

**Issue by mohnewald** [msweetser/check_unifi#3]
We use unifi controllr 5.2.9 and added a "nagios" user with the same password for siteA and siteB.

However only siteA seems to work. siteB fails.

./check_unifi --hostname hotspot.example.net --username nagios --password xxxxxx -v v4 --siteid siteA  ==> Works
./check_unifi --hostname hotspot.example.net --username nagios --password xxxxxx -v v4 --siteid siteB  ==> Does not work:
Traceback (most recent call last):
  File "./check_unifi", line 72, in <module>
    aps = c.get_aps()
  File "/usr/lib/python2.7/site-packages/unifi/controller.py", line 205, in get_aps
    return self._read(self.api_url + 'stat/device', params)
  File "/usr/lib/python2.7/site-packages/unifi/controller.py", line 120, in _read
    res = self.opener.open(url, params)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized

Any ideads on this?

We use v4 but have version 5.2.9.... (since v5 does not work => HTTP Error 401: Unauthorized)

**Comment by codeyy** [comment]
Same here with 5.6.22
